--------------------------------------------------------
--  DDL for Trigger APRES_NOUVEL_ARTICLE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."APRES_NOUVEL_ARTICLE" 
AFTER INSERT ON ARTICLE FOR EACH ROW
DECLARE
  QUANTITE_RESTANTE NUMBER;
BEGIN
  SELECT f.STOCKPAPIER INTO QUANTITE_RESTANTE FROM FORMAT f WHERE f.IDFORMAT = :NEW.IDFORMAT;
  UPDATE_QUANTITE_FORMAT_ARTICLE(:NEW.IDFORMAT,QUANTITE_RESTANTE,:NEW.QUANTITE);
END;
/
ALTER TRIGGER "BROCARCL"."APRES_NOUVEL_ARTICLE" ENABLE;
