--------------------------------------------------------
--  Ref Constraints for Table ARTICLE
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."ARTICLE" ADD CONSTRAINT "FK_ARTICLE_ARTICLE2_COMMANDE" FOREIGN KEY ("IDCOMMANDE")
	  REFERENCES "BROCARCL"."COMMANDE" ("IDCOMMANDE") ENABLE;
 
  ALTER TABLE "BROCARCL"."ARTICLE" ADD CONSTRAINT "FK_ARTICLE_ARTICLE_ALBUM" FOREIGN KEY ("IDALBUM")
	  REFERENCES "BROCARCL"."ALBUM" ("IDALBUM") ENABLE;
 
  ALTER TABLE "BROCARCL"."ARTICLE" ADD CONSTRAINT "FK_ARTICLE_FORMATALB_FORMAT" FOREIGN KEY ("IDFORMAT")
	  REFERENCES "BROCARCL"."FORMAT" ("IDFORMAT") ENABLE;
 
  ALTER TABLE "BROCARCL"."ARTICLE" ADD CONSTRAINT "FK_ARTICLE_REFERENCE_PRESTATA" FOREIGN KEY ("IDPRESTATAIRE")
	  REFERENCES "BROCARCL"."PRESTATAIRE" ("IDPRESTATAIRE") ENABLE;
