--------------------------------------------------------
--  DDL for Trigger AVANT_NOUVEL_ARTICLE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AVANT_NOUVEL_ARTICLE" 
BEFORE INSERT ON ARTICLE FOR EACH ROW
DECLARE
  PRIX_UNITAIRE NUMBER;
  QUANTITE_RESTANTE INTEGER;
BEGIN
  SELECT f.PRIXUNITAIRE, f.STOCKPAPIER INTO PRIX_UNITAIRE, QUANTITE_RESTANTE FROM FORMAT f WHERE f.IDFORMAT = :NEW.IDFORMAT;
  CHECK_QUANTITE_FORMAT_ARTICLE(QUANTITE_RESTANTE,:NEW.QUANTITE);
  :NEW.PRIX := :NEW.QUANTITE * PRIX_UNITAIRE;
END;
/
ALTER TRIGGER "BROCARCL"."AVANT_NOUVEL_ARTICLE" ENABLE;
