--------------------------------------------------------
--  DDL for Trigger AVANT_NOUVELLE_LIVRAISON
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AVANT_NOUVELLE_LIVRAISON" 
BEFORE INSERT OR UPDATE ON LIVRAISON FOR EACH ROW
DECLARE 
DATE_COMMANDE DATE;
DATE_INVALIDE  EXCEPTION;
BEGIN
  SELECT DATECOMMANDE INTO DATE_COMMANDE FROM COMMANDE WHERE IDCOMMANDE IN (SELECT IDCOMMANDE FROM ARTICLE WHERE IDARTICLE = :NEW.IDARTICLE);
  IF (:NEW.DATELIVRAISON < DATE_COMMANDE) THEN
    RAISE DATE_INVALIDE;
  END IF;
  EXCEPTION
  WHEN DATE_INVALIDE THEN
    DBMS_OUTPUT.PUT_LINE ('La date est invalide');
END;
/
ALTER TRIGGER "BROCARCL"."AVANT_NOUVELLE_LIVRAISON" ENABLE;
