--------------------------------------------------------
--  Ref Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."COMMANDE" ADD CONSTRAINT "FK_COMMANDE_PASSAGEDE_CLIENT" FOREIGN KEY ("IDCLIENT")
	  REFERENCES "BROCARCL"."CLIENT" ("IDCLIENT") ENABLE;
 
  ALTER TABLE "BROCARCL"."COMMANDE" ADD CONSTRAINT "FK_COMMANDE_PROMOTION" FOREIGN KEY ("IDPROMOTION")
	  REFERENCES "BROCARCL"."PROMOTION" ("IDPROMOTION") ENABLE;
