--------------------------------------------------------
--  Fichier créé - jeudi-janvier-28-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALBUM
--------------------------------------------------------

  CREATE TABLE "BROCARCL"."ALBUM" 
   (	"IDALBUM" NUMBER(*,0), 
	"IDCLIENT" NUMBER(*,0), 
	"PREFACE" CLOB, 
	"POSTFACE" CLOB, 
	"NBPAGE" NUMBER(*,0), 
	"TYPE" VARCHAR2(10 BYTE), 
	"TITRE" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PREFACE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("POSTFACE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ARTICLE
--------------------------------------------------------

  CREATE TABLE "BROCARCL"."ARTICLE" 
   (	"IDARTICLE" NUMBER(*,0), 
	"IDCOMMANDE" NUMBER(*,0), 
	"IDALBUM" NUMBER(*,0), 
	"IDFORMAT" NUMBER(*,0), 
	"IDPRESTATAIRE" NUMBER(*,0), 
	"QUANTITE" NUMBER(*,0), 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "BROCARCL"."CLIENT" 
   (	"IDCLIENT" NUMBER(*,0), 
	"NOM" CLOB, 
	"PRENOM" CLOB, 
	"ADRESSE" CLOB, 
	"MOT_DE_PASSE" CLOB, 
	"MAIL" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("NOM") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PRENOM") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ADRESSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("MOT_DE_PASSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "BROCARCL"."COMMANDE" 
   (	"IDCOMMANDE" NUMBER(*,0), 
	"IDPROMOTION" NUMBER(*,0), 
	"IDCLIENT" NUMBER(*,0), 
	"DATECOMMANDE" DATE, 
	"PRIXTOTAL" NUMBER, 
	"STATUT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FICHIER
--------------------------------------------------------

  CREATE TABLE "BROCARCL"."FICHIER" 
   (	"IDFICHIER" NUMBER(*,0), 
	"IDCLIENT" NUMBER(*,0), 
	"CHEMIN" CLOB, 
	"PARTAGE" NUMBER(*,0), 
	"PRISEDEVUE" CLOB, 
	"RESOLUTION" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CHEMIN") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PRISEDEVUE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RESOLUTION") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FORMAT
--------------------------------------------------------

  CREATE TABLE "BROCARCL"."FORMAT" 
   (	"IDFORMAT" NUMBER(*,0), 
	"LIBELLE" CLOB, 
	"PRIXUNITAIRE" NUMBER, 
	"RESOLUTIONMINIMALE" CLOB, 
	"VITESSEIMPRESSION" NUMBER, 
	"STOCKPAPIER" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("LIBELLE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RESOLUTIONMINIMALE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table LIVRAISON
--------------------------------------------------------

  CREATE TABLE "BROCARCL"."LIVRAISON" 
   (	"IDLIVRAISON" NUMBER(*,0), 
	"IDARTICLE" NUMBER(*,0), 
	"DATELIVRAISON" DATE, 
	"STATUT" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("STATUT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PHOTO
--------------------------------------------------------

  CREATE TABLE "BROCARCL"."PHOTO" 
   (	"IDPHOTO" NUMBER(*,0), 
	"IDALBUM" NUMBER(*,0), 
	"IDFICHIER" NUMBER(*,0), 
	"TITRE" CLOB, 
	"COMMENTAIRE" CLOB, 
	"PAGE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("TITRE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("COMMENTAIRE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PRESTATAIRE
--------------------------------------------------------

  CREATE TABLE "BROCARCL"."PRESTATAIRE" 
   (	"IDPRESTATAIRE" NUMBER(*,0), 
	"NOM" CLOB, 
	"ADRESSE" CLOB, 
	"TELEPHONE" CLOB, 
	"ACTIVITE" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("NOM") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ADRESSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("TELEPHONE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ACTIVITE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PROMOTION
--------------------------------------------------------

  CREATE TABLE "BROCARCL"."PROMOTION" 
   (	"IDPROMOTION" NUMBER(*,0), 
	"IDCOMMANDE" NUMBER(*,0), 
	"MONTANT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00925246
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."SYS_C00925246" ON "BROCARCL"."ALBUM" ("TITRE", "IDCLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ALBUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."PK_ALBUM" ON "BROCARCL"."ALBUM" ("IDALBUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALBUMCLIENT_FK
--------------------------------------------------------

  CREATE INDEX "BROCARCL"."ALBUMCLIENT_FK" ON "BROCARCL"."ALBUM" ("IDCLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ARTICLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."PK_ARTICLE" ON "BROCARCL"."ARTICLE" ("IDARTICLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ARTICLE_FK
--------------------------------------------------------

  CREATE INDEX "BROCARCL"."ARTICLE_FK" ON "BROCARCL"."ARTICLE" ("IDALBUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00924455
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."SYS_C00924455" ON "BROCARCL"."CLIENT" ("MAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CLIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."PK_CLIENT" ON "BROCARCL"."CLIENT" ("IDCLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_COMMANDE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."PK_COMMANDE" ON "BROCARCL"."COMMANDE" ("IDCOMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PASSAGEDECOMMANDE_FK
--------------------------------------------------------

  CREATE INDEX "BROCARCL"."PASSAGEDECOMMANDE_FK" ON "BROCARCL"."COMMANDE" ("IDCLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FICHIER
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."PK_FICHIER" ON "BROCARCL"."FICHIER" ("IDFICHIER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TELECHARGEMENT_FK
--------------------------------------------------------

  CREATE INDEX "BROCARCL"."TELECHARGEMENT_FK" ON "BROCARCL"."FICHIER" ("IDCLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FORMAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."PK_FORMAT" ON "BROCARCL"."FORMAT" ("IDFORMAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LIVRAISON
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."PK_LIVRAISON" ON "BROCARCL"."LIVRAISON" ("IDLIVRAISON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LIVRAISONCOMMANDE_FK
--------------------------------------------------------

  CREATE INDEX "BROCARCL"."LIVRAISONCOMMANDE_FK" ON "BROCARCL"."LIVRAISON" ("IDARTICLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PHOTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."PK_PHOTO" ON "BROCARCL"."PHOTO" ("IDPHOTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PHOTO_FK
--------------------------------------------------------

  CREATE INDEX "BROCARCL"."PHOTO_FK" ON "BROCARCL"."PHOTO" ("IDFICHIER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00928948
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."SYS_C00928948" ON "BROCARCL"."PHOTO" ("IDALBUM", "IDFICHIER", "PAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PRESTATAIRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."PK_PRESTATAIRE" ON "BROCARCL"."PRESTATAIRE" ("IDPRESTATAIRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROMOTION
--------------------------------------------------------

  CREATE UNIQUE INDEX "BROCARCL"."PK_PROMOTION" ON "BROCARCL"."PROMOTION" ("IDPROMOTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROMOTIONDELIVREE2_FK
--------------------------------------------------------

  CREATE INDEX "BROCARCL"."PROMOTIONDELIVREE2_FK" ON "BROCARCL"."PROMOTION" ("IDCOMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ALBUM
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."ALBUM" ADD CONSTRAINT "PK_ALBUM" PRIMARY KEY ("IDALBUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BROCARCL"."ALBUM" MODIFY ("IDALBUM" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."ALBUM" ADD UNIQUE ("TITRE", "IDCLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ARTICLE
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."ARTICLE" ADD CONSTRAINT "PK_ARTICLE" PRIMARY KEY ("IDARTICLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BROCARCL"."ARTICLE" MODIFY ("IDARTICLE" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."ARTICLE" MODIFY ("IDCOMMANDE" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."ARTICLE" MODIFY ("IDALBUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."CLIENT" ADD CONSTRAINT "PK_CLIENT" PRIMARY KEY ("IDCLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BROCARCL"."CLIENT" MODIFY ("IDCLIENT" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."CLIENT" ADD UNIQUE ("MAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."COMMANDE" ADD CONSTRAINT "PK_COMMANDE" PRIMARY KEY ("IDCOMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BROCARCL"."COMMANDE" ADD CONSTRAINT "STATUT_CHECK" CHECK (statut IN ('creation','en cours','envoi partiel','envoi complet', 'annulee')) ENABLE;
 
  ALTER TABLE "BROCARCL"."COMMANDE" MODIFY ("IDCOMMANDE" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."COMMANDE" MODIFY ("STATUT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FICHIER
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."FICHIER" ADD CONSTRAINT "PK_FICHIER" PRIMARY KEY ("IDFICHIER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BROCARCL"."FICHIER" MODIFY ("IDFICHIER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FORMAT
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."FORMAT" ADD CONSTRAINT "PK_FORMAT" PRIMARY KEY ("IDFORMAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BROCARCL"."FORMAT" MODIFY ("IDFORMAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIVRAISON
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."LIVRAISON" ADD CONSTRAINT "PK_LIVRAISON" PRIMARY KEY ("IDLIVRAISON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BROCARCL"."LIVRAISON" MODIFY ("IDLIVRAISON" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."LIVRAISON" MODIFY ("DATELIVRAISON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PHOTO
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."PHOTO" ADD CONSTRAINT "PK_PHOTO" PRIMARY KEY ("IDPHOTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BROCARCL"."PHOTO" MODIFY ("IDPHOTO" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."PHOTO" MODIFY ("IDALBUM" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."PHOTO" MODIFY ("IDFICHIER" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."PHOTO" MODIFY ("PAGE" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."PHOTO" ADD UNIQUE ("IDALBUM", "IDFICHIER", "PAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRESTATAIRE
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."PRESTATAIRE" ADD CONSTRAINT "PK_PRESTATAIRE" PRIMARY KEY ("IDPRESTATAIRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BROCARCL"."PRESTATAIRE" MODIFY ("IDPRESTATAIRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROMOTION
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."PROMOTION" ADD CONSTRAINT "PK_PROMOTION" PRIMARY KEY ("IDPROMOTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BROCARCL"."PROMOTION" MODIFY ("IDPROMOTION" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."PROMOTION" MODIFY ("IDCOMMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ALBUM
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."ALBUM" ADD CONSTRAINT "FK_ALBUM_ALBUMCLIE_CLIENT" FOREIGN KEY ("IDCLIENT")
	  REFERENCES "BROCARCL"."CLIENT" ("IDCLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ARTICLE
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."ARTICLE" ADD CONSTRAINT "FK_ARTICLE_ARTICLE2_COMMANDE" FOREIGN KEY ("IDCOMMANDE")
	  REFERENCES "BROCARCL"."COMMANDE" ("IDCOMMANDE") ENABLE;
 
  ALTER TABLE "BROCARCL"."ARTICLE" ADD CONSTRAINT "FK_ARTICLE_ARTICLE_ALBUM" FOREIGN KEY ("IDALBUM")
	  REFERENCES "BROCARCL"."ALBUM" ("IDALBUM") ENABLE;
 
  ALTER TABLE "BROCARCL"."ARTICLE" ADD CONSTRAINT "FK_ARTICLE_FORMATALB_FORMAT" FOREIGN KEY ("IDFORMAT")
	  REFERENCES "BROCARCL"."FORMAT" ("IDFORMAT") ENABLE;
 
  ALTER TABLE "BROCARCL"."ARTICLE" ADD CONSTRAINT "FK_ARTICLE_REFERENCE_PRESTATA" FOREIGN KEY ("IDPRESTATAIRE")
	  REFERENCES "BROCARCL"."PRESTATAIRE" ("IDPRESTATAIRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."COMMANDE" ADD CONSTRAINT "FK_COMMANDE_PASSAGEDE_CLIENT" FOREIGN KEY ("IDCLIENT")
	  REFERENCES "BROCARCL"."CLIENT" ("IDCLIENT") ENABLE;
 
  ALTER TABLE "BROCARCL"."COMMANDE" ADD CONSTRAINT "FK_COMMANDE_PROMOTION" FOREIGN KEY ("IDPROMOTION")
	  REFERENCES "BROCARCL"."PROMOTION" ("IDPROMOTION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FICHIER
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."FICHIER" ADD CONSTRAINT "FK_FICHIER_TELECHARG_CLIENT" FOREIGN KEY ("IDCLIENT")
	  REFERENCES "BROCARCL"."CLIENT" ("IDCLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIVRAISON
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."LIVRAISON" ADD CONSTRAINT "FK_LIVRAISO_LIVRAISON_ARTICLE" FOREIGN KEY ("IDARTICLE")
	  REFERENCES "BROCARCL"."ARTICLE" ("IDARTICLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHOTO
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."PHOTO" ADD CONSTRAINT "FK_PHOTO_PHOTO2_ALBUM" FOREIGN KEY ("IDALBUM")
	  REFERENCES "BROCARCL"."ALBUM" ("IDALBUM") ENABLE;
 
  ALTER TABLE "BROCARCL"."PHOTO" ADD CONSTRAINT "FK_PHOTO_PHOTO_FICHIER" FOREIGN KEY ("IDFICHIER")
	  REFERENCES "BROCARCL"."FICHIER" ("IDFICHIER") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROMOTION
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."PROMOTION" ADD CONSTRAINT "FK_PROMOTION_COMMANDE" FOREIGN KEY ("IDCOMMANDE")
	  REFERENCES "BROCARCL"."COMMANDE" ("IDCOMMANDE") ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_ALBUM
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AUTO_INCREMENT_ALBUM" 
before insert on album
for each row
begin
    select album_id_seq.nextval into :new.idalbum from dual;
end;
/
ALTER TRIGGER "BROCARCL"."AUTO_INCREMENT_ALBUM" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AVANT_NOUVEL_ARTICLE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AVANT_NOUVEL_ARTICLE" 
BEFORE INSERT ON ARTICLE FOR EACH ROW
DECLARE
  PRIX_UNITAIRE NUMBER;
  QUANTITE_RESTANTE INTEGER;
BEGIN
  SELECT f.PRIXUNITAIRE, f.STOCKPAPIER INTO PRIX_UNITAIRE, QUANTITE_RESTANTE FROM FORMAT f WHERE f.IDFORMAT = :NEW.IDFORMAT;
  CHECK_QUANTITE_FORMAT_ARTICLE(QUANTITE_RESTANTE,:NEW.QUANTITE);
  :NEW.PRIX := GET_PRIX_ARTICLE(:NEW.QUANTITE,PRIX_UNITAIRE);
END;
/
ALTER TRIGGER "BROCARCL"."AVANT_NOUVEL_ARTICLE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_ARTICLE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AUTO_INCREMENT_ARTICLE" 
before insert on article
for each row
begin
    select article_id_seq.nextval into :new.idarticle from dual;
end;
/
ALTER TRIGGER "BROCARCL"."AUTO_INCREMENT_ARTICLE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger APRES_NOUVEL_ARTICLE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."APRES_NOUVEL_ARTICLE" 
AFTER INSERT ON ARTICLE FOR EACH ROW
DECLARE
  QUANTITE_RESTANTE NUMBER;
BEGIN
  SELECT f.STOCKPAPIER INTO QUANTITE_RESTANTE FROM FORMAT f WHERE f.IDFORMAT = :NEW.IDFORMAT;
  UPDATE_QUANTITE_FORMAT_ARTICLE(:NEW.IDFORMAT,QUANTITE_RESTANTE,:NEW.QUANTITE);
  UPDATE_PRIX_COMMANDE(:NEW.IDCOMMANDE);
END;
/
ALTER TRIGGER "BROCARCL"."APRES_NOUVEL_ARTICLE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_CLIENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AUTO_INCREMENT_CLIENT" 
before insert on client
for each row
begin
    select client_id_seq.nextval into :new.idclient from dual;
end;
/
ALTER TRIGGER "BROCARCL"."AUTO_INCREMENT_CLIENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_COMMANDE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AUTO_INCREMENT_COMMANDE" 
before insert on commande
for each row
begin
    select commande_id_seq.nextval into :new.idcommande from dual;
end;
/
ALTER TRIGGER "BROCARCL"."AUTO_INCREMENT_COMMANDE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOUVELLE_MODIF_COMMANDE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."NOUVELLE_MODIF_COMMANDE" 
AFTER INSERT OR UPDATE ON COMMANDE FOR EACH ROW
BEGIN
  IF (:NEW.STATUT = 'en cours') THEN
    CREATION_PROMOTION(:NEW.IDCOMMANDE,:NEW.PRIXTOTAL);
  END IF;
  NULL;
END;
/
ALTER TRIGGER "BROCARCL"."NOUVELLE_MODIF_COMMANDE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_FICHIER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AUTO_INCREMENT_FICHIER" 
before insert on fichier
for each row
begin
    select fichier_id_seq.nextval into :new.idfichier from dual;
end;
/
ALTER TRIGGER "BROCARCL"."AUTO_INCREMENT_FICHIER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_FORMAT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AUTO_INCREMENT_FORMAT" 
before insert on format
for each row
begin
    select format_id_seq.nextval into :new.idformat from dual;
end;
/
ALTER TRIGGER "BROCARCL"."AUTO_INCREMENT_FORMAT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_LIVRAISON
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AUTO_INCREMENT_LIVRAISON" 
before insert on livraison
for each row
begin
    select livraison_id_seq.nextval into :new.idlivraison from dual;
end;
/
ALTER TRIGGER "BROCARCL"."AUTO_INCREMENT_LIVRAISON" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AVANT_NOUVELLE_LIVRAISON
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AVANT_NOUVELLE_LIVRAISON" 
BEFORE INSERT OR UPDATE ON LIVRAISON FOR EACH ROW
DECLARE 
DATE_COMMANDE DATE;
DATE_INVALIDE  EXCEPTION;
BEGIN
  SELECT DATECOMMANDE INTO DATE_COMMANDE FROM COMMANDE WHERE IDCOMMANDE IN (SELECT IDCOMMANDE FROM ARTICLE WHERE IDARTICLE = :NEW.IDARTICLE);
  IF (:NEW.DATELIVRAISON < DATE_COMMANDE) THEN
    RAISE DATE_INVALIDE;
  END IF;
  EXCEPTION
  WHEN DATE_INVALIDE THEN
    DBMS_OUTPUT.PUT_LINE ('La date est invalide');
END;
/
ALTER TRIGGER "BROCARCL"."AVANT_NOUVELLE_LIVRAISON" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_PHOTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AUTO_INCREMENT_PHOTO" 
before insert on photo
for each row
begin
    select photo_id_seq.nextval into :new.idphoto from dual;
end;
/
ALTER TRIGGER "BROCARCL"."AUTO_INCREMENT_PHOTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_PRESTATAIRE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AUTO_INCREMENT_PRESTATAIRE" 
before insert on prestataire
for each row
begin
    select prestataire_id_seq.nextval into :new.idprestataire from dual;
end;
/
ALTER TRIGGER "BROCARCL"."AUTO_INCREMENT_PRESTATAIRE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INCREMENT_PROMOTION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BROCARCL"."AUTO_INCREMENT_PROMOTION" 
before insert on promotion
for each row
begin
    select promotion_id_seq.nextval into :new.idpromotion from dual;
end;
/
ALTER TRIGGER "BROCARCL"."AUTO_INCREMENT_PROMOTION" ENABLE;
