--------------------------------------------------------
--  Constraints for Table PHOTO
--------------------------------------------------------

  ALTER TABLE "BROCARCL"."PHOTO" ADD CONSTRAINT "PK_PHOTO" PRIMARY KEY ("IDPHOTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BROCARCL"."PHOTO" MODIFY ("IDPHOTO" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."PHOTO" MODIFY ("IDALBUM" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."PHOTO" MODIFY ("IDFICHIER" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."PHOTO" MODIFY ("PAGE" NOT NULL ENABLE);
 
  ALTER TABLE "BROCARCL"."PHOTO" ADD UNIQUE ("IDALBUM", "IDFICHIER", "PAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
